# Generated by Django 3.2.3 on 2021-06-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('idContratacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la Contratacion')),
                ('tipoContratacion', models.CharField(max_length=50, verbose_name='Tipo de Contratacion')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('region', models.CharField(max_length=30, verbose_name='Region')),
                ('comuna', models.CharField(max_length=30, verbose_name='Comuna')),
                ('correo', models.CharField(max_length=30, verbose_name='Correo Electronico')),
                ('contratacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contratacion')),
            ],
        ),
    ]
